apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-demo-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spinnaker-demo-1
  template:
    metadata:
      labels:
        app: spinnaker-demo-1
    spec:
      containers:
      - image: index.docker.io/wurbanski/spinnaker-demo
        name: spinnaker-demo
        ports:
        - containerPort: 80
